services:
  - type: web
    name: nexus-notes-app-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://nexus-notes-app-frontend.onrender.com
      - key: PORT
        value: 10000 